name: Build

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  REGISTRY: ghcr.io
  IMAGE_NAME: bitnami-postgresql-pgvector

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker - Log in to Github Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker - Metadata
        id: docker__metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            bhanunexus/bitnami-postgresql-pgvector
            ${{ env.REGISTRY }}/BhanuNexus/${{ env.IMAGE_NAME }}

      - name: Docker - Build and Push
        id: docker__build-and-push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name != 'pull_request' }}
          file: ./Dockerfile
          tags: ${{ steps.docker__metadata.outputs.tags }}
          labels: ${{ steps.docker__metadata.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/BhanuNexus/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.docker__build-and-push.outputs.digest }}
          push-to-registry: true
